// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Repositories;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(JiaoQiuContext))]
    partial class JiaoQiuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication1.Models.JiaoQiu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChuPanJiao");

                    b.Property<string>("ChuPanRang");

                    b.Property<string>("DangQianJiao");

                    b.Property<string>("DangQianRang");

                    b.Property<string>("DuiMing");

                    b.Property<string>("Half");

                    b.Property<string>("ShePian");

                    b.Property<string>("SheZheng");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
